services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot_network

  redis:
    image: redis:latest
    container_name: redis_cont
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network

  celeryw:
    build: .
    command: celery -A app.celery.app_celery worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    restart: always
    networks:
      - bot_network

  celeryb:
    build: .
    command: celery -A app.celery.app_celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
      - celeryw
    env_file:
      - .env
    restart: always
    networks:
      - bot_network
      
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - bot_network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: