"""Добавить знак зодиака в модель User

Revision ID: b6c9bef6c8d0
Revises: c6ddc27fe3c3
Create Date: 2025-02-20 20:53:51.867991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c9bef6c8d0'
down_revision: Union[str, None] = 'c6ddc27fe3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zodiac_sign', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zodiac_sign')
    # ### end Alembic commands ###
